name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Get version and tag name
      id: version_tag
      run: |
        echo ::set-output name=version::$(echo ${GITHUB_REF#refs/tags/v})
        echo ::set-output name=tag_name::$(echo ${GITHUB_REF#refs/tags/})
    - name: Generate changelog
      id: changelog
      uses: github-script@v5
      with:
        script: |
          const { data } = await github.repos.compareCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            base: 'tags/' + process.env.PREVIOUS_TAG,
            head: 'tags/' + process.env.TAG_NAME
          })
          let changelog = ''
          data.commits.forEach(commit => {
            changelog += - ${commit.commit.message}\n
          })
          console.log(changelog)
          return { changelog }
      env:
        PREVIOUS_TAG: ${{ github.event.release.tag_name }}
        TAG_NAME: ${{ github.event.release.tag_name }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create release issue
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: 'RELEASE: v${{ steps.version_tag.outputs.version }}'
        content-filepath: './release_template.md'
        labels: 'RELEASE'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests
      run: |
        # Run tests here
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
    - name: Add link to release issue
      uses: peter-evans/add-link-comment@v1
      with:
        issue-number: ${{ steps.create_release.outputs.number }}
        message: 'Deployed to https://<username>.github.io/<repo>/'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Close release issue
      uses: peter-evans/close-issue@v1
      with:
        issue-number: ${{ steps.create_release.outputs.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}